// Wire types, generated from recalld by ts-rs (scripts/gen-types.sh); the gate
// fails on drift. Never edit ./generated.
export type { Transcript } from './generated/Transcript';
export type { TranscriptList } from './generated/TranscriptList';
export type { Moment } from './generated/Moment';
export type { Conversation } from './generated/Conversation';
export type { ConversationPage } from './generated/ConversationPage';
export type { CaptureState } from './generated/CaptureState';
export type { SpeakerNames } from './generated/SpeakerNames';
export type { Label } from './generated/Label';
export type { LabelList } from './generated/LabelList';
export type { VocabularyTerm } from './generated/VocabularyTerm';
export type { VocabularyList } from './generated/VocabularyList';
export type { VocabularyRequest } from './generated/VocabularyRequest';
export type { CorrectResult } from './generated/CorrectResult';
export type { Ok } from './generated/Ok';
export type { Session } from './generated/Session';
export type { SessionList } from './generated/SessionList';
export type { SessionRenameRequest } from './generated/SessionRenameRequest';
export type { VoiceNameRequest } from './generated/VoiceNameRequest';
export type { AssignSpanRequest } from './generated/AssignSpanRequest';
export type { AssignResult } from './generated/AssignResult';
export type { CorrectRequest } from './generated/CorrectRequest';
export type { TelemetryEvent } from './generated/TelemetryEvent';
