// Writes the gitignored src/app/build-info.ts with the git sha and build time.
// Embedded rather than fetched, so a stale cached tab shows its own old stamp.
import { execSync } from 'node:child_process';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'src', 'app', 'build-info.ts');

function git(cmd) {
  try {
    return execSync(`git ${cmd}`, { encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

const sha = git('rev-parse --short HEAD') || 'nogit';
// A gitignored build-info.ts won't dirty the tree; any real uncommitted change marks the build.
const dirty = git('status --porcelain') ? '+' : '';
const builtAt = new Date().toISOString();

writeFileSync(
  out,
  `// Generated by scripts/stamp-version.mjs at build time. Do not edit — gitignored.
export const BUILD_INFO = {
  sha: '${sha}${dirty}',
  builtAt: '${builtAt}',
} as const;
`,
);
console.log(`stamped build-info: ${sha}${dirty} @ ${builtAt}`);
