# hm-agents.nix — home-manager module: recall launchd daemons (Mac mini).
#
# Apply after editing (it is a PINNED flake input — the lock must be bumped):
#   1. commit this change in ~/Code/recall
#   2. cd ~/.config/home-manager
#   3. nix flake update recall && home-manager switch --flake .#pippijn
#
# Imported by the personal home-manager flake (~/.config/home-manager), so
# `home-manager switch` installs, reloads and removes these agents declaratively.
# Unlike the xinutec pushers, recall's whole runtime lives in its wrapper scripts
# (scripts/recall*.sh → `nix develop` + the project .venv), so there is NO env to
# fold here — the agents just run the same scripts, and the interpreter is
# unchanged, so no TCC re-grant.
#
# NOTE: recall-live and recall-capture open the microphone (docs/running.md);
# both are migrated with a post-switch check that the mic grant survived the HM
# wrapper — a stable status-0 process (a TCC block would crash-loop instead).
#
# home-manager writes each plist read-only into ~/Library/LaunchAgents with no
# native comment, so a provenance `Comment` key points back here. Do NOT
# hand-edit the generated plists.
{ ... }:

let
  recall = "/Users/pippijn/Code/recall";

  provenance = runs:
    "GENERATED by home-manager from recall/deploy/hm-agents.nix. Do NOT edit "
    + "this file. To change: edit that module + commit, then in "
    + "~/.config/home-manager run 'nix flake update recall && home-manager "
    + "switch --flake .#pippijn'. Runs: ${runs}.";

  # A KeepAlive recall daemon: runs scripts/<script> with <args>, logs to
  # logs/<name>.{out,err}.log at background priority. `extra` adds per-agent keys.
  daemon = { label, name, script, args ? [ ], extra ? { } }: {
    enable = true;
    config = {
      Label = label;
      Comment = provenance (builtins.concatStringsSep " " ([ script ] ++ args));
      ProgramArguments = [ "${recall}/scripts/${script}" ] ++ args;
      RunAtLoad = true;
      KeepAlive = true;
      ProcessType = "Background";
      StandardOutPath = "${recall}/logs/${name}.out.log";
      StandardErrorPath = "${recall}/logs/${name}.err.log";
    } // extra;
  };
in
{
  launchd.agents."com.pippijn.recall-api" = daemon {
    label = "com.pippijn.recall-api";
    name = "api";
    script = "recall.sh";
    args = [ "api" "--out" "/Volumes/Backup/recall" "--host" "0.0.0.0" "--port" "8000" ];
  };

  launchd.agents."com.pippijn.recall-ingest" = daemon {
    label = "com.pippijn.recall-ingest";
    name = "ingest";
    script = "recall-ingest.sh";
  };

  launchd.agents."com.pippijn.recall-worker" = daemon {
    label = "com.pippijn.recall-worker";
    name = "worker";
    script = "recall.sh";
    args = [ "worker" "--loop" "--basic" "--out" "/Volumes/Backup/recall" ];
    # Heavy continuous loop — yield I/O and CPU to interactive work.
    extra = { LowPriorityIO = true; Nice = 10; };
  };

  launchd.agents."com.pippijn.recall-refine" = daemon {
    label = "com.pippijn.recall-refine";
    name = "refine";
    script = "recall-refine.sh";
  };

  # Mic agent — runs .venv/bin/python (a fixed path), so its mic-TCC identity is
  # stable; migrated before capture to prove the grant survives the switch.
  # --device pins the exact CoreAudio input (same pin as recall-capture.sh): the
  # system default input follows whatever connects, e.g. a Bluetooth speaker's
  # hands-free mic.
  # --fleet-url pushes the instant feed to Isis on a background thread (the Isis split):
  # the fleet UI shows live turns within seconds, reconciled when the archive segment
  # lands. Token is RECALL_SYNC_TOKEN (recall.sh sources .env); the push is best-effort
  # and off the VAD loop, so it never affects capture.
  launchd.agents."com.pippijn.recall-live" = daemon {
    label = "com.pippijn.recall-live";
    name = "live";
    script = "recall.sh";
    args = [ "live" "--out" "/Volumes/Backup/recall"
             "--device" "USB Condenser Microphone"
             "--fleet-url" "http://10.100.0.2:8000" ];
  };

  # Mic agent — the critical continuous recording stream (USB mic → segments).
  launchd.agents."com.pippijn.recall-capture" = daemon {
    label = "com.pippijn.recall-capture";
    name = "capture";
    script = "recall-capture.sh";
  };

  # Nightly off-machine mirror (odin). Calendar-scheduled, NOT KeepAlive: it runs
  # once and exits; `recall doctor` alarms if the success marker goes stale. The
  # Mac must push — it is a one-way WireGuard peer the servers cannot reach.
  launchd.agents."com.pippijn.recall-backup" = daemon {
    label = "com.pippijn.recall-backup";
    name = "backup";
    script = "recall-backup.sh";
    extra = {
      KeepAlive = false;
      RunAtLoad = false;
      StartCalendarInterval = [{ Hour = 23; Minute = 30; }];
      LowPriorityIO = true;
    };
  };

  # Is recall actually working? Every 5 minutes, reported to fleetwatch.
  #
  # The check that was missing when it mattered: capture crash-looped on 22 June,
  # recorded nothing for ninety minutes, and was found three weeks later by hand.
  # launchd restarts capture when it dies, so a persistent fault becomes a loop —
  # and a loop looks exactly like a quiet house.
  #
  # The interval MUST match recall.fleetwatch.INTERVAL_S (300): fleetwatch derives
  # staleness from the cadence the report declares, and a producer that stops
  # reporting renders as failed. That is the point — this agent dying, or the Mac
  # dying, is itself the alarm. Nothing here has to detect it.
  launchd.agents."com.pippijn.recall-doctor" = daemon {
    label = "com.pippijn.recall-doctor";
    name = "doctor";
    script = "recall-doctor.sh";
    extra = {
      KeepAlive = false;
      RunAtLoad = true;
      StartInterval = 300;
      LowPriorityIO = true;
    };
  };

  # Push the archive to Isis, the system of record (the Isis split). A timer, not
  # KeepAlive: each run sends only what changed since the last (a transcript-id
  # watermark) and exits. The Mac must push — it is a one-way WireGuard peer the fleet
  # cannot reach. Inert until RECALL_SYNC_TOKEN is set in .env.
  launchd.agents."com.pippijn.recall-sync" = daemon {
    label = "com.pippijn.recall-sync";
    name = "sync";
    script = "recall-sync.sh";
    extra = {
      KeepAlive = false;
      RunAtLoad = true;
      StartInterval = 120;
      LowPriorityIO = true;
      Nice = 10;
    };
  };

  # Mirror Isis's mic pause/resume onto this Mac (the Isis split). A KeepAlive loop that
  # polls Isis every ~5s: Isis holds the desired capture state (its VPN UI) but cannot
  # dial this one-way peer, so control is inverted to a Mac-initiated poll and a pause
  # pressed on the VPN UI takes hold within seconds. Lightweight — an HTTP round trip,
  # no ML. Inert until RECALL_SYNC_TOKEN is set in .env.
  launchd.agents."com.pippijn.recall-capture-mirror" = daemon {
    label = "com.pippijn.recall-capture-mirror";
    name = "capture-mirror";
    script = "recall-capture-mirror.sh";
  };
}
