"""Emit `transcript/src/latin_ranges.rs`: the alphabetic codepoints whose
Unicode name contains "LATIN".

Rust has no dependency-free way to read character names, and guessing at block
boundaries gets the edges wrong, so the table is derived from Python's
`unicodedata` and frozen.

Run: python3 scripts/gen_latin_ranges.py > transcript/src/latin_ranges.rs
"""

from __future__ import annotations

import sys
import unicodedata


def ranges() -> list[tuple[int, int]]:
    """Every contiguous run of alphabetic codepoints named "LATIN ..."."""
    out: list[tuple[int, int]] = []
    start: int | None = None
    prev = 0
    for cp in range(0x110000):
        c = chr(cp)
        if c.isalpha() and "LATIN" in unicodedata.name(c, ""):
            if start is None:
                start = cp
            prev = cp
        elif start is not None:
            out.append((start, prev))
            start = None
    if start is not None:
        out.append((start, prev))
    return out


def main() -> int:
    rows = ranges()
    print("//! Generated by `scripts/gen_latin_ranges.py`; do not edit.")
    print("//!")
    print('//! The alphabetic codepoints whose Unicode name contains "LATIN"')
    print(f"//! (Unicode {unicodedata.unidata_version}).")
    print()
    print("/// `(first, last)` inclusive, sorted, non-overlapping.")
    print(f"pub const LATIN_RANGES: [(u32, u32); {len(rows)}] = [")
    for lo, hi in rows:
        print(f"    (0x{lo:04X}, 0x{hi:04X}),")
    print("];")
    return 0


if __name__ == "__main__":
    sys.exit(main())
