"""Emit `recalld/src/latin_ranges.rs` — the codepoint ranges Python calls LATIN.

⚠ The Rust port of `foreign_script_ratio` must agree with the Python it replaces
on the EDGES, and the Python asked whether a character's Unicode NAME contains
"LATIN". There is no dependency-free Rust equivalent, and guessing at block
boundaries is how the two quietly disagree — so the answer is derived from the
same table Python used and frozen here.

Run: python3 scripts/gen_latin_ranges.py > recalld/src/latin_ranges.rs
"""

from __future__ import annotations

import sys
import unicodedata


def ranges() -> list[tuple[int, int]]:
    """Every contiguous run of codepoints that is alphabetic and named LATIN."""
    out: list[tuple[int, int]] = []
    start: int | None = None
    prev = 0
    for cp in range(0x110000):
        c = chr(cp)
        if c.isalpha() and "LATIN" in unicodedata.name(c, ""):
            if start is None:
                start = cp
            prev = cp
        elif start is not None:
            out.append((start, prev))
            start = None
    if start is not None:
        out.append((start, prev))
    return out


def main() -> int:
    rows = ranges()
    print("//! GENERATED by `scripts/gen_latin_ranges.py` — do not edit by hand.")
    print("//!")
    print("//! Every codepoint range Python's `unicodedata` names LATIN, from")
    print(f"//! Unicode {unicodedata.unidata_version}: a character is Latin when its")
    print("//! name says so, and these ranges are that rule precomputed.")
    print()
    print("/// `(first, last)` inclusive, sorted, non-overlapping.")
    print(f"pub const LATIN_RANGES: [(u32, u32); {len(rows)}] = [")
    for lo, hi in rows:
        print(f"    (0x{lo:04X}, 0x{hi:04X}),")
    print("];")
    return 0


if __name__ == "__main__":
    sys.exit(main())
