//! The port agrees with the implementation it replaces — on 120 random cases,
//! not only on the six hand-written ones.
//!
//! ⚠ The fixture was generated BY `recall.align` (seed 20260911), so it pins that
//! implementation's behaviour at the moment of the port: the tie-break in
//! `speaker_at`, the order `smooth` picks offenders in, the trim. Shared unit
//! tests cannot catch a divergence in any of those, because both sides were
//! written to pass them.
//!
//! When `recall.align` is deleted this fixture stops being a parity check and
//! becomes a plain regression corpus. That is the intended end state, and it is
//! why the cases are stored rather than generated at test time — nothing here
//! may depend on Python existing.

use recalld::align::{MIN_TURN_S, SpeakerTurn, Word, assign_words_to_speakers};
use serde::Deserialize;

#[derive(Deserialize)]
struct Expected {
    speaker: String,
    start: f64,
    end: f64,
    text: String,
    confidence: f64,
    words: Vec<Word>,
}

#[derive(Deserialize)]
struct Case {
    words: Vec<Word>,
    turns: Vec<SpeakerTurn>,
    expected: Vec<Expected>,
}

#[test]
fn the_rust_alignment_matches_the_python_one_case_for_case() {
    let raw = include_str!("fixtures/align-parity.json");
    let cases: Vec<Case> = serde_json::from_str(raw).expect("fixture");
    assert!(cases.len() >= 120, "the corpus must not silently shrink");
    let mut with_output = 0;
    for (index, case) in cases.iter().enumerate() {
        let got = assign_words_to_speakers(&case.words, &case.turns, MIN_TURN_S);
        assert_eq!(
            got.len(),
            case.expected.len(),
            "case {index}: turn count differs"
        );
        if !got.is_empty() {
            with_output += 1;
        }
        for (turn, want) in got.iter().zip(case.expected.iter()) {
            assert_eq!(turn.speaker, want.speaker, "case {index}: speaker");
            assert_eq!(turn.text, want.text, "case {index}: text");
            assert!(
                (turn.start - want.start).abs() < 1e-9,
                "case {index}: start {} vs {}",
                turn.start,
                want.start
            );
            assert!(
                (turn.end - want.end).abs() < 1e-9,
                "case {index}: end {} vs {}",
                turn.end,
                want.end
            );
            assert!(
                (turn.confidence - want.confidence).abs() < 1e-9,
                "case {index}: confidence {} vs {}",
                turn.confidence,
                want.confidence
            );
            assert_eq!(turn.words, want.words, "case {index}: words");
        }
    }
    // A corpus that aligned to nothing would pass every assertion above.
    assert!(
        with_output > 100,
        "only {with_output} cases produced turns — the corpus is not exercising the aligner"
    );
}
